### ISSUE TITLE
Error in example: And() got an unexpected keyword argument 'ctx'

### ISSUE THREAD

**Issue by michaelmior** [VeriEQL/VeriEQL#2]
When trying to run the example with Python 3.11 and z3 4.8.7, I get the error below.

```
Traceback (most recent call last):
  File "/home/mmior/apps/VeriEQL/__main__.py", line 52, in <module>
    main(sql1, sql2, schema, ROW_NUM=bound_size, constraints=constants, **config)
  File "/home/mmior/apps/VeriEQL/__main__.py", line 11, in main
    env.add_constraints(constraints)
  File "/home/mmior/apps/VeriEQL/environment.py", line 756, in add_constraints
    constraint = _f(constraint)
                 ^^^^^^^^^^^^^^
  File "/home/mmior/apps/VeriEQL/environment.py", line 620, in _f
    out = And(*out)
          ^^^^^^^^^
  File "/home/mmior/apps/VeriEQL/constants.py", line 33, in <lambda>
    And = lambda *args: Z3_And(*args, ctx=Z3_CONTEXT)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: And() got an unexpected keyword argument 'ctx'
```

**Comment by michaelmior** [comment]
It turns out this works when using the version of the library in `z3py_libs`. It seems like the code no longer works without these modifications.

**Comment by whatsmyname** [comment]
> It turns out this works when using the version of the library in z3py_libs. It seems like the code no longer works without these modifications.

Yes. Please replace orginal z3 codes with these files since they would accelerate formulation considerably.

**Comment by michaelmior** [comment]
@whatsmyname My point is that it doesn't work at all without those replacements. It would help if this was more clearly documented.

**Comment by whatsmyname** [comment]
Hi @michaelmior. Thanks for your suggestion. We'd like to make it clearer.

**Comment by mrigger** [comment]
Ran into the same issue. As @michaelmior pointed out, it would be great to reflect this in the documentation.
